server {
    listen 3000;
    root /app;
    index index.html;
    client_max_body_size 100M;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    location /uploaded_files/ {
        alias /var/data/uploaded_files/;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        client_max_body_size 100M;
    }
}
